argument_specs:
  main:
    short_description: nginx
    description: "Deploy nginx container."
    author: dudecalledbro
    options:
      nginx_docker_image:
        type: str
        required: true
        description: "Specifies the nginx docker image to be used."
      nginx_docker_path:
        type: str
        required: true
        description: "Defines the deployment path for nginx."
      nginx_docker_owner:
        type: str
        required: true
        description: "Defines the deployment owner for nginx."
      nginx_docker_group:
        type: str
        required: true
        description: "Defines the deployment group for nginx."
      nginx_docker_certs:
        type: list
        required: false
        elements: dict
        description: "Specify nginx tls certificates."
      nginx_docker_upstreams:
        type: list
        required: false
        elements: dict
        description: "Specify nginx docker upstream hosts."
      nginx_docker_vhosts:
        type: list
        required: true
        elements: dict
        description: "Specify nginx docker vhosts."
