# Specify nginx tls certificates
nginx_docker_certs:
- name: tls.crt
  content: "{{ lookup('ansible.builtin.file', inventory_dir + '/certs/tls.crt') }}"
- name: tls.key
  content: "{{ lookup('ansible.builtin.file', inventory_dir + '/certs/tls.key') }}"

# Specify nginx docker vhosts
# yamllint disable rule:indentation
nginx_docker_vhosts:
- listen: 80
  server_name: semaphore.example.com
  config: |
    return 301 https://$host$request_uri;

- listen: 443
  listen_extra: ssl
  server_name: semaphore.example.com
  config: |
    ssl_certificate /certs/tls.crt;
    ssl_certificate_key /certs/tls.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    ssl_ciphers EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH;

    location / {
      proxy_pass http://semaphore/;
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_buffering off;
      proxy_request_buffering off;
    }

    location /api/ws {
      proxy_pass http://semaphore/api/ws;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Origin "";
    }
# yamllint enable rule:indentation
