- name: Restart mysql container
  ansible.builtin.command: >-
    docker compose --ansi never --progress plain restart
  args:
    chdir: "{{ mysql_docker_path }}"
  changed_when: true
  listen: restart mysql
