- name: Create postgres directory
  ansible.builtin.file:
    path: "{{ postgres_docker_path }}"
    owner: "{{ postgres_docker_owner }}"
    group: "{{ postgres_docker_group }}"
    state: directory
    mode: 0755

- name: Create postgres docker compose deployment
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ postgres_docker_path }}/docker-compose.yml"
    owner: "{{ postgres_docker_owner }}"
    group: "{{ postgres_docker_group }}"
    trim_blocks: false
    mode: 0644
  notify: restart postgres

- name: Validate postgres docker compose deployment
  ansible.builtin.command: docker compose config --quiet
  args:
    chdir: "{{ postgres_docker_path }}"
  changed_when: false

- name: Startup postgres docker compose deployment
  ansible.builtin.command: >-
    docker compose --ansi never --progress plain up --detach
  args:
    chdir: "{{ postgres_docker_path }}"
  register: postgres_container_startup
  changed_when: "'Started' in postgres_container_startup.stdout"
